//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModUploader.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModUploader.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        public static string Edit_Browse {
            get {
                return ResourceManager.GetString("Edit_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changelog: 的本地化字符串。
        /// </summary>
        public static string Edit_Changelog {
            get {
                return ResourceManager.GetString("Edit_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Edit_Confirm {
            get {
                return ResourceManager.GetString("Edit_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edits will not be saved. Continue? 的本地化字符串。
        /// </summary>
        public static string Edit_ConfirmCancel {
            get {
                return ResourceManager.GetString("Edit_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please confirm that you have reviewed all details before uploading. 的本地化字符串。
        /// </summary>
        public static string Edit_ConfirmUpload {
            get {
                return ResourceManager.GetString("Edit_ConfirmUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content Folder: 的本地化字符串。
        /// </summary>
        public static string Edit_ContentFolder {
            get {
                return ResourceManager.GetString("Edit_ContentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Tags: 的本地化字符串。
        /// </summary>
        public static string Edit_CustomTags {
            get {
                return ResourceManager.GetString("Edit_CustomTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press Enter to add 的本地化字符串。
        /// </summary>
        public static string Edit_CustomTags_PlaceHolder {
            get {
                return ResourceManager.GetString("Edit_CustomTags_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string Edit_Description {
            get {
                return ResourceManager.GetString("Edit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string Edit_Name {
            get {
                return ResourceManager.GetString("Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to change the preview image 的本地化字符串。
        /// </summary>
        public static string Edit_PreviewImage_Tooltip {
            get {
                return ResourceManager.GetString("Edit_PreviewImage_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field is required. 的本地化字符串。
        /// </summary>
        public static string Edit_Required {
            get {
                return ResourceManager.GetString("Edit_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Item Type 的本地化字符串。
        /// </summary>
        public static string Edit_SelectType {
            get {
                return ResourceManager.GetString("Edit_SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Preview Image Only 的本地化字符串。
        /// </summary>
        public static string Edit_UpdatePreviewOnly {
            get {
                return ResourceManager.GetString("Edit_UpdatePreviewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Edit_Upload {
            get {
                return ResourceManager.GetString("Edit_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Item 的本地化字符串。
        /// </summary>
        public static string Home_Create {
            get {
                return ResourceManager.GetString("Home_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Item 的本地化字符串。
        /// </summary>
        public static string Home_Update {
            get {
                return ResourceManager.GetString("Home_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome, {0}! 的本地化字符串。
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create item: 的本地化字符串。
        /// </summary>
        public static string Main_CreateFail {
            get {
                return ResourceManager.GetString("Main_CreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to initialize Steam API. 的本地化字符串。
        /// </summary>
        public static string Main_InitFail {
            get {
                return ResourceManager.GetString("Main_InitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to update mod: 的本地化字符串。
        /// </summary>
        public static string Main_UpdateFail {
            get {
                return ResourceManager.GetString("Main_UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Failed: 的本地化字符串。
        /// </summary>
        public static string ModInfo_QueryFail {
            get {
                return ResourceManager.GetString("ModInfo_QueryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t seem to have any items... 的本地化字符串。
        /// </summary>
        public static string Select_NoItems {
            get {
                return ResourceManager.GetString("Select_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No results found. 的本地化字符串。
        /// </summary>
        public static string Select_NoResults {
            get {
                return ResourceManager.GetString("Select_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for Workshop ID or name 的本地化字符串。
        /// </summary>
        public static string Select_SearchBox {
            get {
                return ResourceManager.GetString("Select_SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the items to be updated 的本地化字符串。
        /// </summary>
        public static string Select_Title {
            get {
                return ResourceManager.GetString("Select_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open log file 的本地化字符串。
        /// </summary>
        public static string Upload_OpenLog {
            get {
                return ResourceManager.GetString("Upload_OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully upload! 的本地化字符串。
        /// </summary>
        public static string Upload_Success {
            get {
                return ResourceManager.GetString("Upload_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading... 的本地化字符串。
        /// </summary>
        public static string Upload_Uploading {
            get {
                return ResourceManager.GetString("Upload_Uploading", resourceCulture);
            }
        }
    }
}
