//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModUploader.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_EResult {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_EResult() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModUploader.Resources.Resource.EResult", typeof(Resource_EResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Access is denied 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccessDenied {
            get {
                return ResourceManager.GetString("k_EResultAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many changes to this account 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountActivityLimitExceeded {
            get {
                return ResourceManager.GetString("k_EResultAccountActivityLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current account has been associated with multiple partners 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountAssociatedToMultiplePartners {
            get {
                return ResourceManager.GetString("k_EResultAccountAssociatedToMultiplePartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account is disabled 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountDisabled {
            get {
                return ResourceManager.GetString("k_EResultAccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many accounts accessing this resource 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountLimitExceeded {
            get {
                return ResourceManager.GetString("k_EResultAccountLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current user&apos;s account is currently locked for use, likely due to hijacking and pending ownership verification 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountLockedDown {
            get {
                return ResourceManager.GetString("k_EResultAccountLockedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need two-factor code to login 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountLoginDeniedNeedTwoFactor {
            get {
                return ResourceManager.GetString("k_EResultAccountLoginDeniedNeedTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login attempt failed, try to throttle response to possible attacker 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountLoginDeniedThrottle {
            get {
                return ResourceManager.GetString("k_EResultAccountLoginDeniedThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account login denied due to 2nd factor authentication failure 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountLogonDenied {
            get {
                return ResourceManager.GetString("k_EResultAccountLogonDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account login denied due to 2nd factor auth failure - and no mail has been sent 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountLogonDeniedNoMail {
            get {
                return ResourceManager.GetString("k_EResultAccountLogonDeniedNoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The logon failed because the account&apos;s email is not verified 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountLogonDeniedVerifiedEmailRequired {
            get {
                return ResourceManager.GetString("k_EResultAccountLogonDeniedVerifiedEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account is not featured 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountNotFeatured {
            get {
                return ResourceManager.GetString("k_EResultAccountNotFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account not found 的本地化字符串。
        /// </summary>
        internal static string k_EResultAccountNotFound {
            get {
                return ResourceManager.GetString("k_EResultAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator privileges granted 的本地化字符串。
        /// </summary>
        internal static string k_EResultAdministratorOK {
            get {
                return ResourceManager.GetString("k_EResultAdministratorOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User is already logged in elsewhere 的本地化字符串。
        /// </summary>
        internal static string k_EResultAlreadyLoggedInElsewhere {
            get {
                return ResourceManager.GetString("k_EResultAlreadyLoggedInElsewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All the games in this guest pass redemption request are already owned by the user 的本地化字符串。
        /// </summary>
        internal static string k_EResultAlreadyOwned {
            get {
                return ResourceManager.GetString("k_EResultAlreadyOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guest pass has already been redeemed by account, cannot be used again 的本地化字符串。
        /// </summary>
        internal static string k_EResultAlreadyRedeemed {
            get {
                return ResourceManager.GetString("k_EResultAlreadyRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Response due to a Parse failure, missing field, etc. 的本地化字符串。
        /// </summary>
        internal static string k_EResultBadResponse {
            get {
                return ResourceManager.GetString("k_EResultBadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user is VAC2 banned 的本地化字符串。
        /// </summary>
        internal static string k_EResultBanned {
            get {
                return ResourceManager.GetString("k_EResultBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A user blocked the action 的本地化字符串。
        /// </summary>
        internal static string k_EResultBlocked {
            get {
                return ResourceManager.GetString("k_EResultBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Called method is busy - action not taken 的本地化字符串。
        /// </summary>
        internal static string k_EResultBusy {
            get {
                return ResourceManager.GetString("k_EResultBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation has been canceled, typically by user (e.g. content download) 的本地化字符串。
        /// </summary>
        internal static string k_EResultCancelled {
            get {
                return ResourceManager.GetString("k_EResultCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested new password is not legal 的本地化字符串。
        /// </summary>
        internal static string k_EResultCannotUseOldPassword {
            get {
                return ResourceManager.GetString("k_EResultCannotUseOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to connect 的本地化字符串。
        /// </summary>
        internal static string k_EResultConnectFailed {
            get {
                return ResourceManager.GetString("k_EResultConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content version mismatch 的本地化字符串。
        /// </summary>
        internal static string k_EResultContentVersion {
            get {
                return ResourceManager.GetString("k_EResultContentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation canceled because data is ill formed or unrecoverable 的本地化字符串。
        /// </summary>
        internal static string k_EResultDataCorruption {
            get {
                return ResourceManager.GetString("k_EResultDataCorruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested service has been configured to be unavailable 的本地化字符串。
        /// </summary>
        internal static string k_EResultDisabled {
            get {
                return ResourceManager.GetString("k_EResultDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation canceled - not enough disk space 的本地化字符串。
        /// </summary>
        internal static string k_EResultDiskFull {
            get {
                return ResourceManager.GetString("k_EResultDiskFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name is not unique 的本地化字符串。
        /// </summary>
        internal static string k_EResultDuplicateName {
            get {
                return ResourceManager.GetString("k_EResultDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The request is a duplicate and the action has already occurred in the past, ignored this time 的本地化字符串。
        /// </summary>
        internal static string k_EResultDuplicateRequest {
            get {
                return ResourceManager.GetString("k_EResultDuplicateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot send an email 的本地化字符串。
        /// </summary>
        internal static string k_EResultEmailSendFailure {
            get {
                return ResourceManager.GetString("k_EResultEmailSendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encryption or Decryption failed 的本地化字符串。
        /// </summary>
        internal static string k_EResultEncryptionFailure {
            get {
                return ResourceManager.GetString("k_EResultEncryptionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License/Guest pass the user is trying to access is expired 的本地化字符串。
        /// </summary>
        internal static string k_EResultExpired {
            get {
                return ResourceManager.GetString("k_EResultExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account login denied due to an expired auth code 的本地化字符串。
        /// </summary>
        internal static string k_EResultExpiredLoginAuthCode {
            get {
                return ResourceManager.GetString("k_EResultExpiredLoginAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External account (PSN, Facebook...) is already linked to some other account, must explicitly request to replace/delete the link first 的本地化字符串。
        /// </summary>
        internal static string k_EResultExternalAccountAlreadyLinked {
            get {
                return ResourceManager.GetString("k_EResultExternalAccountAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External account (PSN, Facebook...) is not linked to a Steam account 的本地化字符串。
        /// </summary>
        internal static string k_EResultExternalAccountUnlinked {
            get {
                return ResourceManager.GetString("k_EResultExternalAccountUnlinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Facebook query returned an error 的本地化字符串。
        /// </summary>
        internal static string k_EResultFacebookQueryError {
            get {
                return ResourceManager.GetString("k_EResultFacebookQueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generic failure 的本地化字符串。
        /// </summary>
        internal static string k_EResultFail {
            get {
                return ResourceManager.GetString("k_EResultFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File was not found 的本地化字符串。
        /// </summary>
        internal static string k_EResultFileNotFound {
            get {
                return ResourceManager.GetString("k_EResultFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A game server login token owned by this token&apos;s owner has been banned 的本地化字符串。
        /// </summary>
        internal static string k_EResultGSLTDenied {
            get {
                return ResourceManager.GetString("k_EResultGSLTDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Game Server Login Token (GSLT) has expired from disuse; it can be reset for use 的本地化字符串。
        /// </summary>
        internal static string k_EResultGSLTExpired {
            get {
                return ResourceManager.GetString("k_EResultGSLTExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game server owner is denied for some other reason such as account locked, community ban, VAC ban, missing phone, etc. 的本地化字符串。
        /// </summary>
        internal static string k_EResultGSOwnerDenied {
            get {
                return ResourceManager.GetString("k_EResultGSOwnerDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The authentication handshake has failed 的本地化字符串。
        /// </summary>
        internal static string k_EResultHandshakeFailed {
            get {
                return ResourceManager.GetString("k_EResultHandshakeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The users hardware does not support Intel&apos;s Identity Protection Technology (IPT) 的本地化字符串。
        /// </summary>
        internal static string k_EResultHardwareNotCapableOfIPT {
            get {
                return ResourceManager.GetString("k_EResultHardwareNotCapableOfIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target is ignoring sender 的本地化字符串。
        /// </summary>
        internal static string k_EResultIgnored {
            get {
                return ResourceManager.GetString("k_EResultIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested new password is not allowed 的本地化字符串。
        /// </summary>
        internal static string k_EResultIllegalPassword {
            get {
                return ResourceManager.GetString("k_EResultIllegalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User doesn&apos;t have enough wallet funds to complete the action 的本地化字符串。
        /// </summary>
        internal static string k_EResultInsufficientFunds {
            get {
                return ResourceManager.GetString("k_EResultInsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient privilege 的本地化字符串。
        /// </summary>
        internal static string k_EResultInsufficientPrivilege {
            get {
                return ResourceManager.GetString("k_EResultInsufficientPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The files submitted to the CEG server are not valid 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidCEGSubmission {
            get {
                return ResourceManager.GetString("k_EResultInvalidCEGSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The email was invalid 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidEmail {
            get {
                return ResourceManager.GetString("k_EResultInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of thing we were requested to act on is invalid 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidItemType {
            get {
                return ResourceManager.GetString("k_EResultInvalidItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account login denied due to auth code invalid 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidLoginAuthCode {
            get {
                return ResourceManager.GetString("k_EResultInvalidLoginAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name was invalid 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidName {
            get {
                return ResourceManager.GetString("k_EResultInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A parameter is incorrect 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidParam {
            get {
                return ResourceManager.GetString("k_EResultInvalidParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password/ticket is invalid 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidPassword {
            get {
                return ResourceManager.GetString("k_EResultInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol version is incorrect 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidProtocolVer {
            get {
                return ResourceManager.GetString("k_EResultInvalidProtocolVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Called object was in an invalid state 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidState {
            get {
                return ResourceManager.GetString("k_EResultInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Steam ID was invalid 的本地化字符串。
        /// </summary>
        internal static string k_EResultInvalidSteamID {
            get {
                return ResourceManager.GetString("k_EResultInvalidSteamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There has been a generic IO failure 的本地化字符串。
        /// </summary>
        internal static string k_EResultIOFailure {
            get {
                return ResourceManager.GetString("k_EResultIOFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IP address has been banned from taking this action 的本地化字符串。
        /// </summary>
        internal static string k_EResultIPBanned {
            get {
                return ResourceManager.GetString("k_EResultIPBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The login failed due to an IP restriction 的本地化字符串。
        /// </summary>
        internal static string k_EResultIPLoginRestrictionFailed {
            get {
                return ResourceManager.GetString("k_EResultIPLoginRestrictionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP address not found 的本地化字符串。
        /// </summary>
        internal static string k_EResultIPNotFound {
            get {
                return ResourceManager.GetString("k_EResultIPNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intel&apos;s Identity Protection Technology (IPT) has failed to initialize 的本地化字符串。
        /// </summary>
        internal static string k_EResultIPTInitError {
            get {
                return ResourceManager.GetString("k_EResultIPTInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item we are trying to access has been deleted 的本地化字符串。
        /// </summary>
        internal static string k_EResultItemDeleted {
            get {
                return ResourceManager.GetString("k_EResultItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too much of a good thing 的本地化字符串。
        /// </summary>
        internal static string k_EResultLimitExceeded {
            get {
                return ResourceManager.GetString("k_EResultLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to acquire access lock for this operation 的本地化字符串。
        /// </summary>
        internal static string k_EResultLockingFailed {
            get {
                return ResourceManager.GetString("k_EResultLockingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user is logged in elsewhere 的本地化字符串。
        /// </summary>
        internal static string k_EResultLoggedInElsewhere {
            get {
                return ResourceManager.GetString("k_EResultLoggedInElsewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The logon session has been replaced 的本地化字符串。
        /// </summary>
        internal static string k_EResultLogonSessionReplaced {
            get {
                return ResourceManager.GetString("k_EResultLogonSessionReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user needs to provide a valid captcha 的本地化字符串。
        /// </summary>
        internal static string k_EResultNeedCaptcha {
            get {
                return ResourceManager.GetString("k_EResultNeedCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Steam client doesn&apos;t have a connection to the back-end 的本地化字符串。
        /// </summary>
        internal static string k_EResultNoConnection {
            get {
                return ResourceManager.GetString("k_EResultNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing matching the request found 的本地化字符串。
        /// </summary>
        internal static string k_EResultNoMatch {
            get {
                return ResourceManager.GetString("k_EResultNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no URL matching the provided values 的本地化字符串。
        /// </summary>
        internal static string k_EResultNoMatchingURL {
            get {
                return ResourceManager.GetString("k_EResultNoMatchingURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account does not have a mobile device associated with it 的本地化字符串。
        /// </summary>
        internal static string k_EResultNoMobileDevice {
            get {
                return ResourceManager.GetString("k_EResultNoMobileDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user is not logged on 的本地化字符串。
        /// </summary>
        internal static string k_EResultNotLoggedOn {
            get {
                return ResourceManager.GetString("k_EResultNotLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data has not been modified 的本地化字符串。
        /// </summary>
        internal static string k_EResultNotModified {
            get {
                return ResourceManager.GetString("k_EResultNotModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t perform operation until payment has settled 的本地化字符串。
        /// </summary>
        internal static string k_EResultNotSettled {
            get {
                return ResourceManager.GetString("k_EResultNotSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string k_EResultOK {
            get {
                return ResourceManager.GetString("k_EResultOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed due to parental control restrictions for current user 的本地化字符串。
        /// </summary>
        internal static string k_EResultParentalControlRestricted {
            get {
                return ResourceManager.GetString("k_EResultParentalControlRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to authenticate password for a session kick 的本地化字符串。
        /// </summary>
        internal static string k_EResultPasswordRequiredToKickSession {
            get {
                return ResourceManager.GetString("k_EResultPasswordRequiredToKickSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password could not be verified as it&apos;s unset server side 的本地化字符串。
        /// </summary>
        internal static string k_EResultPasswordUnset {
            get {
                return ResourceManager.GetString("k_EResultPasswordUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request is pending, it may be in process or waiting on third party 的本地化字符串。
        /// </summary>
        internal static string k_EResultPending {
            get {
                return ResourceManager.GetString("k_EResultPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to write change to the data store 的本地化字符串。
        /// </summary>
        internal static string k_EResultPersistFailed {
            get {
                return ResourceManager.GetString("k_EResultPersistFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many changes to this phone 的本地化字符串。
        /// </summary>
        internal static string k_EResultPhoneActivityLimitExceeded {
            get {
                return ResourceManager.GetString("k_EResultPhoneActivityLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PSN ticket was invalid 的本地化字符串。
        /// </summary>
        internal static string k_EResultPSNTicketInvalid {
            get {
                return ResourceManager.GetString("k_EResultPSNTicketInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temporary rate limit exceeded, try again later, different from k_EResultLimitExceeded which may be permanent 的本地化字符串。
        /// </summary>
        internal static string k_EResultRateLimitExceeded {
            get {
                return ResourceManager.GetString("k_EResultRateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot refund to payment method, must use wallet 的本地化字符串。
        /// </summary>
        internal static string k_EResultRefundToWallet {
            get {
                return ResourceManager.GetString("k_EResultRefundToWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The action could not be completed because it is region restricted 的本地化字符串。
        /// </summary>
        internal static string k_EResultRegionLocked {
            get {
                return ResourceManager.GetString("k_EResultRegionLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The remote or IPC call has failed 的本地化字符串。
        /// </summary>
        internal static string k_EResultRemoteCallFailed {
            get {
                return ResourceManager.GetString("k_EResultRemoteCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The remote server has disconnected 的本地化字符串。
        /// </summary>
        internal static string k_EResultRemoteDisconnect {
            get {
                return ResourceManager.GetString("k_EResultRemoteDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The sync cannot resume due to a conflict between the local and remote files 的本地化字符串。
        /// </summary>
        internal static string k_EResultRemoteFileConflict {
            get {
                return ResourceManager.GetString("k_EResultRemoteFileConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user cannot complete the action until they re-enter their password 的本地化字符串。
        /// </summary>
        internal static string k_EResultRequirePasswordReEntry {
            get {
                return ResourceManager.GetString("k_EResultRequirePasswordReEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device being used is not allowed to perform this action 的本地化字符串。
        /// </summary>
        internal static string k_EResultRestrictedDevice {
            get {
                return ResourceManager.GetString("k_EResultRestrictedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access has been revoked (used for revoked guest passes) 的本地化字符串。
        /// </summary>
        internal static string k_EResultRevoked {
            get {
                return ResourceManager.GetString("k_EResultRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New value is the same as the old one (used for secret question and answer) 的本地化字符串。
        /// </summary>
        internal static string k_EResultSameAsPreviousValue {
            get {
                return ResourceManager.GetString("k_EResultSameAsPreviousValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The service is in a read-only state 的本地化字符串。
        /// </summary>
        internal static string k_EResultServiceReadOnly {
            get {
                return ResourceManager.GetString("k_EResultServiceReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested service is currently unavailable 的本地化字符串。
        /// </summary>
        internal static string k_EResultServiceUnavailable {
            get {
                return ResourceManager.GetString("k_EResultServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to find the shopping cart requested 的本地化字符串。
        /// </summary>
        internal static string k_EResultShoppingCartNotFound {
            get {
                return ResourceManager.GetString("k_EResultShoppingCartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS code failure - no match, none pending, etc. 的本地化字符串。
        /// </summary>
        internal static string k_EResultSmsCodeFailed {
            get {
                return ResourceManager.GetString("k_EResultSmsCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long running operation has suspended/paused (e.g. content download) 的本地化字符串。
        /// </summary>
        internal static string k_EResultSuspended {
            get {
                return ResourceManager.GetString("k_EResultSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time presented is out of range or tolerance 的本地化字符串。
        /// </summary>
        internal static string k_EResultTimeNotSynced {
            get {
                return ResourceManager.GetString("k_EResultTimeNotSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation timed out 的本地化字符串。
        /// </summary>
        internal static string k_EResultTimeout {
            get {
                return ResourceManager.GetString("k_EResultTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are too many of this thing pending already 的本地化字符串。
        /// </summary>
        internal static string k_EResultTooManyPending {
            get {
                return ResourceManager.GetString("k_EResultTooManyPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try another Content Manager 的本地化字符串。
        /// </summary>
        internal static string k_EResultTryAnotherCM {
            get {
                return ResourceManager.GetString("k_EResultTryAnotherCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The activation code for two-factor authentication (Steam Guard) didn&apos;t match 的本地化字符串。
        /// </summary>
        internal static string k_EResultTwoFactorActivationCodeMismatch {
            get {
                return ResourceManager.GetString("k_EResultTwoFactorActivationCodeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two-factor authentication (Steam Guard) code is incorrect 的本地化字符串。
        /// </summary>
        internal static string k_EResultTwoFactorCodeMismatch {
            get {
                return ResourceManager.GetString("k_EResultTwoFactorCodeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something happened that we didn&apos;t expect to ever happen 的本地化字符串。
        /// </summary>
        internal static string k_EResultUnexpectedError {
            get {
                return ResourceManager.GetString("k_EResultUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value entered is outside the acceptable range 的本地化字符串。
        /// </summary>
        internal static string k_EResultValueOutOfRange {
            get {
                return ResourceManager.GetString("k_EResultValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Upload_ChooseContentFolder_Cansel {
            get {
                return ResourceManager.GetString("Upload_ChooseContentFolder_Cansel", resourceCulture);
            }
        }
    }
}
