//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModUploader.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModUploader.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid or missing parameters. 的本地化字符串。
        /// </summary>
        internal static string Command_Error {
            get {
                return ResourceManager.GetString("Command_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available arguments:
        ///&quot;-help&quot; Show this part
        ///&quot;-update &lt;id&gt; &lt;content_path&gt;  [&lt;previewImage_path&gt; (Ignoring this item will not change the preview image)]&quot; Update a mod
        ///&quot;-newmod &lt;title&gt; &lt;content_path&gt; [&lt;previewImage_path&gt; (Ignore this will use default preview image)]&quot; Create a new mod 的本地化字符串。
        /// </summary>
        internal static string Command_Help {
            get {
                return ResourceManager.GetString("Command_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create mod: 的本地化字符串。
        /// </summary>
        internal static string Main_CreateFail {
            get {
                return ResourceManager.GetString("Main_CreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid content path or/and preview image path. 的本地化字符串。
        /// </summary>
        internal static string Main_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Main_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input. Please try again. 的本地化字符串。
        /// </summary>
        internal static string Main_InvalidInput {
            get {
                return ResourceManager.GetString("Main_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your mod&apos;s workshop ID or URL to update your mod, or vaild operation:
        ///- &apos;mymod&apos; show your mods in a list
        ///- &apos;newmod&apos; create a new mod
        ///- &apos;exit&apos; exit 的本地化字符串。
        /// </summary>
        internal static string Main_Message {
            get {
                return ResourceManager.GetString("Main_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App is already running. 的本地化字符串。
        /// </summary>
        internal static string Main_MultiInstances {
            get {
                return ResourceManager.GetString("Main_MultiInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your new mod&apos;s description (optional): 的本地化字符串。
        /// </summary>
        internal static string Main_NewMod_EnterDescription {
            get {
                return ResourceManager.GetString("Main_NewMod_EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your new mod&apos;s title (cannot be empty): 的本地化字符串。
        /// </summary>
        internal static string Main_NewMod_EnterTitle {
            get {
                return ResourceManager.GetString("Main_NewMod_EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting mod info... 的本地化字符串。
        /// </summary>
        internal static string Main_Update_Getinfo {
            get {
                return ResourceManager.GetString("Main_Update_Getinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod will update: 的本地化字符串。
        /// </summary>
        internal static string Main_Update_WillUpdate {
            get {
                return ResourceManager.GetString("Main_Update_WillUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to update mod: 的本地化字符串。
        /// </summary>
        internal static string Main_UpdateFail {
            get {
                return ResourceManager.GetString("Main_UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item does not appear to yours: 的本地化字符串。
        /// </summary>
        internal static string ModInfo_NotAuthor {
            get {
                return ResourceManager.GetString("ModInfo_NotAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item does not appear to be a Cities: Skylines workshop item: 的本地化字符串。
        /// </summary>
        internal static string ModInfo_NotCSL {
            get {
                return ResourceManager.GetString("ModInfo_NotCSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item do not appear to be a mod: 的本地化字符串。
        /// </summary>
        internal static string ModInfo_NotMod {
            get {
                return ResourceManager.GetString("ModInfo_NotMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Failed: 的本地化字符串。
        /// </summary>
        internal static string ModInfo_QueryFailed {
            get {
                return ResourceManager.GetString("ModInfo_QueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You canceled the selection. 的本地化字符串。
        /// </summary>
        internal static string Upload_ChooseContentFolder_Cancel {
            get {
                return ResourceManager.GetString("Upload_ChooseContentFolder_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose your mod content folder 的本地化字符串。
        /// </summary>
        internal static string Upload_ChooseContentFolder_Title {
            get {
                return ResourceManager.GetString("Upload_ChooseContentFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You canceled the selection. Will use the default image. 的本地化字符串。
        /// </summary>
        internal static string Upload_ChoosePreviewImageFile_OpenFileDialog_Cancel_Newmod {
            get {
                return ResourceManager.GetString("Upload_ChoosePreviewImageFile_OpenFileDialog_Cancel_Newmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You canceled the selection. Will not change the image. 的本地化字符串。
        /// </summary>
        internal static string Upload_ChoosePreviewImageFile_OpenFileDialog_Cancel_Update {
            get {
                return ResourceManager.GetString("Upload_ChoosePreviewImageFile_OpenFileDialog_Cancel_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose the preview image 的本地化字符串。
        /// </summary>
        internal static string Upload_ChoosePreviewImageFile_OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("Upload_ChoosePreviewImageFile_OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to provide a preview image? 的本地化字符串。
        /// </summary>
        internal static string Upload_ChoosePreviewImageFile_TaskDialog_InstructionText_Newmod {
            get {
                return ResourceManager.GetString("Upload_ChoosePreviewImageFile_TaskDialog_InstructionText_Newmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to update the preview image? 的本地化字符串。
        /// </summary>
        internal static string Upload_ChoosePreviewImageFile_TaskDialog_InstructionText_Update {
            get {
                return ResourceManager.GetString("Upload_ChoosePreviewImageFile_TaskDialog_InstructionText_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click &quot;Yes&quot; to select the image, or click &quot;No&quot; to skip and use the default image. 的本地化字符串。
        /// </summary>
        internal static string Upload_ChoosePreviewImageFile_TaskDialog_Text_NewMod {
            get {
                return ResourceManager.GetString("Upload_ChoosePreviewImageFile_TaskDialog_Text_NewMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click &quot;Yes&quot; to select the image, or click &quot;No&quot; to skip without changing the image. 的本地化字符串。
        /// </summary>
        internal static string Upload_ChoosePreviewImageFile_TaskDialog_Text_Update {
            get {
                return ResourceManager.GetString("Upload_ChoosePreviewImageFile_TaskDialog_Text_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workshop item {0} is successfully created. 的本地化字符串。
        /// </summary>
        internal static string Upload_CreateSuccess {
            get {
                return ResourceManager.GetString("Upload_CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating workshop item, please wait... 的本地化字符串。
        /// </summary>
        internal static string Upload_Creating {
            get {
                return ResourceManager.GetString("Upload_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetching your mod list, please wait... 的本地化字符串。
        /// </summary>
        internal static string Upload_GetModList_Fetching {
            get {
                return ResourceManager.GetString("Upload_GetModList_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t seem to have any mods... 的本地化字符串。
        /// </summary>
        internal static string Upload_GetModList_NoMod {
            get {
                return ResourceManager.GetString("Upload_GetModList_NoMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully upload! Opening workshop page for you... 的本地化字符串。
        /// </summary>
        internal static string Upload_Success {
            get {
                return ResourceManager.GetString("Upload_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading... 的本地化字符串。
        /// </summary>
        internal static string Upload_Uploading {
            get {
                return ResourceManager.GetString("Upload_Uploading", resourceCulture);
            }
        }
    }
}
